// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var foo: String

    public var foo0: String

    enum CodingKeys: String, CodingKey {
        case foo = "Foo"
        case foo0 = "foo"
    }
}
