// Code generated by jtd-codegen for Swift v0.2.1
import Foundation

/// A Geometry object represents points, curves, and surfaces in coordinate
/// space.  Every Geometry object is a GeoJSON object no matter where it
/// occurs in a GeoJSON text.
/// 
/// o  The value of a Geometry object's "type" member MUST be one of the
///     seven geometry types (see Section 1.4).
/// 
/// o  A GeoJSON Geometry object of any type other than
///     "GeometryCollection" has a member with the name "coordinates". The
///     value of the "coordinates" member is an array.  The structure of the
///     elements in this array is determined by the type of geometry.
///     GeoJSON processors MAY interpret Geometry objects with empty
///     "coordinates" arrays as null objects.
// Discriminator GeojsonObject: NOT IMPLEMENTED
