// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

/// For type "MultiPoint", the "coordinates" member is an array of
/// positions.
// DiscriminatorVariant GeojsonObjectMultiPoint: NOT IMPLEMENTED
