// Code generated by jtd-codegen for Swift v0.2.1
import Foundation

/// For type "LineString", the "coordinates" member is an array of two
/// or more positions.
// DiscriminatorVariant GeojsonObjectLineString: NOT IMPLEMENTED
