// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

/// For type "Polygon", the "coordinates" member MUST be an array of
/// linear ring coordinate arrays.
// DiscriminatorVariant GeojsonObjectPolygon: NOT IMPLEMENTED
