// Code generated by jtd-codegen for Swift v0.2.1
import Foundation

/// For type "MultiPolygon", the "coordinates" member is an array of
/// Polygon coordinate arrays.
// DiscriminatorVariant GeojsonObjectMultiPolygon: NOT IMPLEMENTED
