// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

/// For type "MultiLineString", the "coordinates" member is an array of
/// LineString coordinate arrays.
// DiscriminatorVariant GeojsonObjectMultiLineString: NOT IMPLEMENTED
