// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    /// A description for discriminator
    public var discriminatorWithDescription: RootDiscriminatorWithDescription

    /// A description for enum
    public var enumWithDescription: RootEnumWithDescription

    /// Whereas disregard and contempt for human rights have resulted in
    /// barbarous acts which have outraged the conscience of mankind, and the
    /// advent of a world in which human beings shall enjoy freedom of speech
    /// and belief and freedom from fear and want has been proclaimed as the
    /// highest aspiration of the common people,
    public var longDescription: String

    /// A description for properties
    public var propertiesWithDescription: RootPropertiesWithDescription

    /// A description for ref
    public var refWithDescription: Baz

    /// A description for string
    public var stringWithDescription: String

    enum CodingKeys: String, CodingKey {
        case discriminatorWithDescription = "discriminator_with_description"
        case enumWithDescription = "enum_with_description"
        case longDescription = "long_description"
        case propertiesWithDescription = "properties_with_description"
        case refWithDescription = "ref_with_description"
        case stringWithDescription = "string_with_description"
    }
}
