// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

/// A description for enum
public enum RootEnumWithDescription: String, Codable {
    /// A description for X
    case x = "X"

    /// A description for Y
    case y = "Y"

    /// A description for Z
    case z = "Z"
}
