// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootFoo: Codable {
    public var bar: RootFooBar

    enum CodingKeys: String, CodingKey {
        case bar = "bar"
    }
}
