// Code generated by jtd-codegen for Swift v0.2.1
import Foundation

public struct Root0: Codable {
    public var bar: String

    public var baz: [Bool]>

    public var foo: Bool

    public var quux: [Bool]>
}
