// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var foo: Timestamp?

    enum CodingKeys: String, CodingKey {
        case foo = "foo"
    }

    init(from decoder: Decoder) throws {
        var container = decoder.container(keyedBy: CodingKeys.self)

        self.foo = try container.decode(Timestamp?.self, forKey: foo)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(self.foo, forKey: foo)
    }
}
