// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var foo: Timestamp?

    enum CodingKeys: String, CodingKey {
        case foo = "foo"
    }
}
