// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var foo: RootFoo

    public var fooBar: RootFooBar0

    enum CodingKeys: String, CodingKey {
        case foo = "foo"
        case fooBar = "foo_bar"
    }
}
