// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootFooBar: Codable {
    public var x: Bool

    enum CodingKeys: String, CodingKey {
        case x = "x"
    }
}
