// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootFooBar0: Codable {
    public var x: String

    enum CodingKeys: String, CodingKey {
        case x = "x"
    }
}
