// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var notnullRefNotnullString: NotnullRefNotnullString

    public var notnullRefNullString: NotnullRefNullString

    public var notnullString: NotnullString

    public var nullRefNotnullString: NullRefNotnullString

    public var nullRefNullString: NullRefNullString

    public var nullString: NullString
}
