// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var notnullRefNotnullString: NotnullRefNotnullString

    public var notnullRefNullString: NotnullRefNullString

    public var notnullString: NotnullString

    public var nullRefNotnullString: NullRefNotnullString

    public var nullRefNullString: NullRefNullString

    public var nullString: NullString

    enum CodingKeys: String, CodingKey {
        case notnullRefNotnullString = "notnull_ref_notnull_string"
        case notnullRefNullString = "notnull_ref_null_string"
        case notnullString = "notnull_string"
        case nullRefNotnullString = "null_ref_notnull_string"
        case nullRefNullString = "null_ref_null_string"
        case nullString = "null_string"
    }

    init(from decoder: Decoder) throws {
        var container = decoder.container(keyedBy: CodingKeys.self)

        self.notnullRefNotnullString = try container.decode(NotnullRefNotnullString.self, forKey: notnullRefNotnullString)
        self.notnullRefNullString = try container.decode(NotnullRefNullString.self, forKey: notnullRefNullString)
        self.notnullString = try container.decode(NotnullString.self, forKey: notnullString)
        self.nullRefNotnullString = try container.decode(NullRefNotnullString.self, forKey: nullRefNotnullString)
        self.nullRefNullString = try container.decode(NullRefNullString.self, forKey: nullRefNullString)
        self.nullString = try container.decode(NullString.self, forKey: nullString)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(self.notnullRefNotnullString, forKey: notnullRefNotnullString)
        try container.encode(self.notnullRefNullString, forKey: notnullRefNullString)
        try container.encode(self.notnullString, forKey: notnullString)
        try container.encode(self.nullRefNotnullString, forKey: nullRefNotnullString)
        try container.encode(self.nullRefNullString, forKey: nullRefNullString)
        try container.encode(self.nullString, forKey: nullString)
    }
}
