// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootBar: Codable {
    public var baz: String

    enum CodingKeys: String, CodingKey {
        case baz = "baz"
    }

    init(from decoder: Decoder) throws {
        var container = decoder.container(keyedBy: CodingKeys.self)

        self.baz = try container.decode(String.self, forKey: baz)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(self.baz, forKey: baz)
    }
}
