// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var for_: For

    public var object: Object

    enum CodingKeys: String, CodingKey {
        case for_ = "for"
        case object = "object"
    }

    init(from decoder: Decoder) throws {
        var container = decoder.container(keyedBy: CodingKeys.self)

        self.for_ = try container.decode(For.self, forKey: for_)
        self.object = try container.decode(Object.self, forKey: object)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(self.for_, forKey: for_)
        try container.encode(self.object, forKey: object)
    }
}
