// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var for_: For

    public var object: Object

    enum CodingKeys: String, CodingKey {
        case for_ = "for"
        case object = "object"
    }
}
