// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootQuux: Codable {
    public var quuz: String

    enum CodingKeys: String, CodingKey {
        case quuz = "quuz"
    }

    init(from decoder: Decoder) throws {
        var container = decoder.container(keyedBy: CodingKeys.self)

        self.quuz = try container.decode(String.self, forKey: quuz)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(self.quuz, forKey: quuz)
    }
}
