// Code generated by jtd-codegen for Swift v0.2.1
import Foundation

public struct Root: Codable {
    public var overrideElementsContainer: [String]>

    public var overrideTypeDiscriminator: RootOverrideTypeDiscriminator

    public var overrideTypeEnum: RootOverrideTypeEnum

    public var overrideTypeExpr: String

    public var overrideTypeProperties: RootOverrideTypeProperties

    public var overrideValuesContainer: [String: String]
}
