// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var http: String

    public var id: String

    public var nestedIdInitialism: RootNestedIdInitialism

    public var utf8: String

    public var wordWithEmbeddedIdInitialism: String

    public var wordWithTrailingInitialismId: String
}
