// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public var http: String

    public var id: String

    public var nestedIdInitialism: RootNestedIdInitialism

    public var utf8: String

    public var wordWithEmbeddedIdInitialism: String

    public var wordWithTrailingInitialismId: String

    enum CodingKeys: String, CodingKey {
        case http = "http"
        case id = "id"
        case nestedIdInitialism = "nested_id_initialism"
        case utf8 = "utf8"
        case wordWithEmbeddedIdInitialism = "word_with_embedded_id_initialism"
        case wordWithTrailingInitialismId = "word_with_trailing_initialism_id"
    }
}
